### ISSUE TITLE
Exporting more than just the best match

### ISSUE THREAD

**Issue by hbarsnes** [compomics/COSS#8]
Would it be possible to include more than just the best match when exporting the results? Preferably by adding an additional column with the rank of each match per spectrum?

It would also be nice to be able to include the decoy hits in the exports?

**Comment by Genet-Abay** [comment]
All the matched library spectra are now exported to the output file with their respective rank. 1 represents the highest-ranked matched library spectrum.

**Comment by hbarsnes** [comment]
Thanks! However, I cannot really test this as I now only get 43 rows in the export compared to 11332 rows I got before (i.e. the same as the number of spectra in the mgf file). I've tried to do some debugging but have not been able to figure out what is going wrong. 

Perhaps you can have a look? I've shared the data here: https://www.dropbox.com/s/fajvmp3benix501/Human_annotated.zip?dl=0. I'm using the default settings in COSS.

BTW, regarding the decoy hits in the exports, would it not make more sense to reverse the values in the Library column to 1 meaning that a hit is in the library and 0 meaning that it is not? At least I was confused about this being the other way around and had to check the code to make sure. ;)

**Comment by Genet-Abay** [comment]
Fixed! I have also searched the data you have shared here and here is the result: https://www.dropbox.com/preview/result_qExactive01819/qExactive01819_MsRobin.xlsx?role=personal

Values for decoy and library in the Library column are switched. you are right it makes sense that way.

The validation column contains values only for the first rank of each identified spectrum and 'NA' for other ranks.

**Comment by hbarsnes** [comment]
Thanks for the fix! However, I'm afraid I still get only 12 hits when searching the data I shared above. Are you sure that you pushed all of the changes?

> I have also searched the data you have shared here and here is the result: https://www.dropbox.com/preview/result_qExactive01819/qExactive01819_MsRobin.xlsx?role=personal

This link does not seem to work. I think it would be better if you shared it via "Copy Dropbox link" instead of as a direct link to the file?

> Values for decoy and library in the Library column are switched. you are right it makes sense that way.

Thanks!

> The validation column contains values only for the first rank of each identified spectrum and 'NA' for other ranks.

Would it be possible to also get the values for the lower ranking hits or perhaps these are not recorded?

**Comment by Genet-Abay** [comment]
Now it should work. Dependencies are built. Deadlock also fixed.
here is the result I got.
https://www.dropbox.com/s/arhzgjp12x7ffsa/qExactive01819_new_MsRobin.xlsx?dl=0

**Comment by hbarsnes** [comment]
Yes, seems to work now! I will rerun my search with the new reverse decoys and let you know how it goes. :)
